# Generated by Django 2.0 on 2018-01-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
